baseURL = "http://nicolai.ruckel.de"
theme = "nicolai"
languageCode = "en-us"
title = "awesome website"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[params]
  subtitle = "the most awesome website in the internet"
  copyright = "© 2017 Nicolai Ruckel. All rights reserved."
