baseURL = "http://nicolai.ruckel.de"
theme = "nicolai"
languageCode = "en-us"
title = "Nicolai Ruckel"

pygmentsCodefences = true
pygmentsUseClasses = true

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[params]
  subtitle = ""
  copyright = "© 2018 Nicolai Ruckel"
  mail = "mailto:nicolai@ruckel.de"
  github = "https://github.com/NicolaiRuckel"
  twitter = "https://twitter.com/NicolaiRuckel"
