baseURL = "http://nicolai.ruckel.de"
theme = "nicolai"
languageCode = "en-us"
title = "awesome website"

pygmentsCodefences = true
pygmentsUseClasses = true

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[params]
  subtitle = "the most awesome website in the internet"
  copyright = "© 2017 Nicolai Ruckel"
  mail = "mailto:nicolai@ruckel.de"
  github = "https://github.com/RanaExMachina"
  instagram = "https://www.instagram.com/der_bassist/"
  twitter = "https://twitter.com/RanaExMachina"
